config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#deposit"

  resources :users, only: [:index, :show] do
    resources :bottles, only: [:new, :create, :index, :show, :destroy]
  end

  resources :users do
    resources :bookings
  end

 # get "zipcode", to: "pages#zipcode", as: "zipcode"

   get "bottles/new", to: "bottles#new"
  # post "bottles", to: "bottles#create"
  # get "users/:id", to: "users#show"

  # get "bookings/:id", to: "bookings#show"
  # get "/index", to: "pages#index"
  # get "bottles/:id", to: "bottles#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user

  def self.price_calculator(type, number)
    case type
    when "Cans"
      return number * 0.25
    when "Plastic"
      return number * 0.15
    when "Glass"
      return number * 0.08
    else
      return 0
    end
  end
end

app/models/time_availability.rb
class TimeAvailability < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name zipcode password email provider photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end



  def after_sign_up_path_for(resource)
    user_bookings_path(current_user)
  end
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @user = current_user
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.save
    redirect_to user_booking_path(current_user, @booking)
  end

  def show
    @booking = Booking.find(params[:user_id])
    @user = User.find(params[:user_id])
  end

  private

  def booking_params
    params.require(:booking).permit(:bottle_type, :quantity, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[home deposit]

  def home
  end

  def zipcode
  end

  def deposit
  end

  def index
    @bottles = Bottle.all
  end

  def show
    @bottles = Bottle.find(params[:id])
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create

  end

  def show

    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Welcome to Dashboard</h1>

<%= link_to "Create collection", new_user_booking_path(current_user), class: "btn btn-primary" %>

app/views/bookings/new.html.erb
<h1>Create Collection</h1>
<div data-controller="form">
  <%= simple_form_for [@user, @booking] do |f| %>
    <%= f.input :bottle_type, collection: ["Plastic", "Glass", "Cans"], input_html: {data: {form_target: "bottleType", action: "change->form#calculateValue"}} %>
    <%= f.input :quantity, collection: (1..10), input_html: {data: {form_target: "quantity", action: "change->form#calculateValue"}} %>
    <%= f.input :price, disabled: true, input_html: {data: {form_target: "cost"}} %>
    <%= f.submit 'Send'%>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="card-category">
    <div class="d-flex justify-content-center">
      <div class="cards">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
              <div class="card-trip">
                <img src="https://images.unsplash.com/photo-1561414926-7f3f921a2e18?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=872&q=80" />
                <div class="card-trip-infos">
                  <div>
                    <div class="container">
                      <% @user.bookings.each do |booking| %>
                      <%= booking.quantity %>
                      <%= booking.bottle_type %>
                      <%= booking.price %>
                      <br>
                      <% end %>
                    </div>
                  <h2 class="card-trip-pricing">£99.99</h2>
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
                </div>
              </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bottles/index.html.erb
<h1>All Bottles</h1>

<%= @bottles %>

app/views/bottles/new.html.erb
<div class="d-flex justify-content-center">

<%# <h1>Lets give the collector more infos..</h1>
</div>

<div class="d-flex row justify-content-center">
<h5>How many glass bottles do you have?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Quantity">
  <input type="submit">
</form>

<h5>How many petbottles do you have?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Quantity">
  <input type="submit">
</form>

<h5>How many cans do you have?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Quantity">
  <input type="submit">
</form>

<h5>In wich floor do you live?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Ex. 1. floor?">
  <input type="submit">
</form>

<h5>Can you help carring the bottles to the ground floor?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Yes / No?">
  <input type="submit">
</form>

<h5>Do you confirm you are only offering refundable bottles?</h5>
<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Yes / No?">
  <input type="submit">
</form>

</div> %>


<%= form_with model: @bottle do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :zipcode %>
  <%= f.number_field :zipcode %>
  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.submit %>
<% end %>

</div>
<%# (:user_id, :first_name, :last_name, :zipcode, :password, :email, :provider) %>

app/views/bottles/show.html.erb
<h1>text</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deposit</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

      <%= render "shared/navbar" %>
      <div class="container">
        <%# <p class="notice"><%= notice %>
        <%# <p class="alert"><%= alert %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/deposit.html.erb
<div class="bg-image">
    <div class="banner">
      <h1>Bottle-me <strong>connecting people</strong> to <strong>help each other</strong>!</h1>

      <p><span data-controller="typed-js"></span></p>

      <% if user_signed_in? %>
        <div class="p-2"><%= link_to "Provide bottles",   new_user_booking_path(current_user) , class:"btn btn-ghost"%></div>
      <% else %>
        <div class="p-2"><%= link_to "Discover provider",  new_user_registration_path(:user_type => "provider") , class:"btn btn-ghost"%></div>          <div class="p-2">  <%= link_to "Discover collector",  new_user_registration_path(:user_type => "collector") , class:"btn btn-ghost"%></div>
      <% end %>
</div>

app/views/pages/index.html.erb
<h1>This is our index page.</h1>

<ul>
  <% @bottles.each do |bottle| %>
    <li><%= bottle.name %></li>
    <li><%= bottle.name %></li>
  <% end %>
</ul>

app/views/pages/zipcode.html.erb
<h1>Where are you located?</h1>

app/views/shared/_card.html.erb
<div class="card-trip">
 <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
    <div class="card-trip-infos">
      <div>
        <div class="container">
          <% @user.bookings.each do |booking| %>
            <%= booking.quantity %>
              %= booking.bottle_type %>
              <br>
            <% end %>
        </div>
        <h2 class="card-trip-pricing">£99.99</h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-md navbar-light bg-faded">

  <div class="navbar navbar-expand-md navbar-light navbar-lewagon bg-faded fixed-top">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <img src="https://img.uxwing.com/wp-content/themes/uxwing/download/food-drinks-cooking/plastic-bottle-icon.svg" alt="" width="30" height="24" class="d-inline-block align-text-top" />
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
 
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out",  destroy_user_session_path, data:{ turbo_method: :delete }, class:"dropdown-item"%>
              <%= link_to "Log in",  new_user_session_path, class:"dropdown-item" %>
            </div>
          </li>
          <% else %>
          <%= link_to "Log in",  new_user_session_path, class:"dropdown-item" %>
          <% end %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>
</nav>

app/views/users/home.html.erb
<h1>Hi, im the users home</h1>
<h1>Thousand bottles for you </h1>
<h1>🍾</h1>

app/views/users/new.html.erb
<h1>Create a new deposit</h1>

app/views/users/show.html.erb
<div class="bg-image d-flex justify-content-center align-items-center"
  style="
    background-image: url('https://images.unsplash.com/photo-1520537867678-1253af0c55ef?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1310&q=80');
    height: 100vh;
    width: 100vw;
    z-index: -1;

    opacity: 0.5;
    background-repeat: repeat;
  ">


  <div class="container">
    <div class="row">

      <div class="col-6">
        <h1>Your balance</h1>
      </div>

      <div class="col-6">
        <h1>Balance</h1>
      </div>
    </div>
</div>